version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro
    environment:
      - ENVIRONMENT_MODE=development
    command: npm run start-dev

