version: '3'
services:
  node-app:
    container_name: express-node-app-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    environment:
      - ENVIRONMENT_MODE=development
    env_file:
      - ./.env

